config/routes.rb
Rails.application.routes.draw do

  root 'orders#new'

  get '/auth/:provider/callback', to: 'sessions#create'
  
  resources :orders, only: [:create, :index, :new]

  resources :users, only: [:index, :show, :create, :update, :new]

  get '/signup' => "users#new"


  post '/getquote' => 'orders#get_quote'
  post '/confirm' => 'orders#create_remote_order'


# ======= Static Pages =======
  get 'welcome/about'
  get 'welcome/index'

# ======= Sessions ROUTES ======= 
  get '/login' => 'sessions#new'
  get '/auth/twitter/', to: 'sessions#create_twitter_session', as: :twitter
  get '/auth/:provider/callback', to: 'sessions#create_twitter_session'
  post '/login' => 'sessions#create' 
  delete '/logout' => 'sessions#destroy'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user

  
end

app/models/role.rb
class Role < ActiveRecord::Base
has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base

	belongs_to :address
	belongs_to :role
	has_many :orders
	validates :name, presence: true
	# validates :email, presence: true, unless: :twitter_login?
	attr_reader :password
	has_secure_password
	# validates :password, presence: true, unless: :twitter_login?

	def twitter_login?
		self.uid ? true : false
	end
	 
	def self.find_or_create_from_auth_hash(auth_hash)
	  user = User.where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
	  user.update(
	    username: auth_hash.info.nickname,
	    name: auth_hash.info.name,
	    profile_image: auth_hash.info.image,
	    token: auth_hash.credentials.token,
	    secret: auth_hash.credentials.secret
	  )
	  user
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

private 
  def current_user 
	@current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

end #closes application controller

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	# @response = HTTParty.post(
	# 	"https://api.scalablepress.com/v2/order/",
	# 	:basic_auth => auth,
	# 	:headers => {'Content-Type' => 'application/json'},
	# 	:body => {"orderToken":"order_E61NFfzipHnDMB-KOpu_Hw"}.to_json
	# 	)

	def auth
		{:password => ENV['scalable_press_test_key']}
	end

	def index
		@orders = HTTParty.get("https://api.scalablepress.com/v2/order/", :basic_auth => auth)
	end


	def new
		@order = Order.new
	end


	def create
		@size = params[:order][:size]
		@quantity = params[:order][:quantity]

		# @design_id = get_design_id
		# @order_token = get_order_token(@design_id, @size, @quantity)
		# @remote_order = create_remote_order(@order_token)

		@order = Order.new

		if @order.save
			redirect_to root_path
		else
			render :new
		end
	end



	def get_design_id
		@response = HTTParty.post(
			"https://api.scalablepress.com/v2/design/",
			:headers => {'Content-Type' => 'application/json'},
			:basic_auth => auth,
			:body => {
		    "type":"screenprint",
		    "sides": {
		        "front": {
		          "colors": [
		            "white"
		          ],
		          "dimensions": {
		            "width": 5
		          },
		          "position": {
		            "horizontal": "C",
		            "offset": {
		              "top": 2.5
		            }
		          },
		          "artwork": "http://ga.kyleconkright.com/mks/img.eps"
		        }
		    }
		}.to_json
		)
		return @response["designId"]
	end

	def get_quote
		design_id = get_design_id
		size = params[:size]
		qty = params[:qty]

		@response = HTTParty.post(
			"https://api.scalablepress.com/v2/quote/",
			:headers => {'Content-Type' => 'application/json'},
			:basic_auth => auth,
			:body => {
		    "type":"screenprint",
		    "sides":{"front":"1"},
		    "products":[
		        {
		            "id":"american-apparel-50-50-t-shirt",
		            "color":"heather black",
		            "quantity":qty,
		            "size":size
		        }
		    ],
		    "address": {
		        "name": "My Customer",
		        "address1": "123 Scalable Drive",
		        "city": "West Pressfield",
		        "state": "CA",
		        "zip": "90210",
		        "country": "US"
		    },
		    "designId":design_id
		}.to_json
		)
		@response
		render :json => @response
	end


	def create_remote_order
		order_token = params[:order_token]
		@response = HTTParty.post(
			"https://api.scalablepress.com/v2/order/",
			:headers => {'Content-Type' => 'application/json'},
			:basic_auth => auth,
			:body => {"orderToken":order_token}.to_json
		)
		@response
		render :json => @response

	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create 
		user = User.find_by(email: params[:login][:email])
		if user && user.authenticate(params[:login][:password]) 
		session[:user_id] = user.id.to_s 
		redirect_to root_path 
		else 
		  redirect_to login_path 
		end 
end

def create_twitter_session
	@user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id.to_s 
    redirect_to root_path
end

def destroy 
# delete that key/value pair in our sessions hash 
  session.delete(:user_id) 
  redirect_to login_path
end 

protected
  def auth_hash
    request.env['omniauth.auth']
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
  	 @user = User.new(user_params)
      if @user.save
      	 session[:user_id] = @user.id.to_s 
		 redirect_to root_path
	  else 
	  	render :new
	  end
	end


private
	def user_params 
		params.require(:user).permit(:name, :email, :password) 
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end

	def about
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mks</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
<!--         <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> -->
      </button>
      <a class="navbar-brand" href="#">TweetShirt.io</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">MY ACCOUNT<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">

              <li>
                <% if current_user %><%= current_user.name %></li>
              <li>
                <%= link_to 'LOG OUT', logout_path, method: :delete %> 
                <% else %> 
                <%= link_to 'LOGIN', login_path %> 
                <%= link_to 'SIGN UP', new_user_path %> 
              </li>
                <% end %>
            </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

<!-- made an edit to nothing -->
<!-- make another change -->

app/views/layouts/test.html.erb
<p>this is a git test page</p>

app/views/orders/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
		<h1>Update Order Notes</h1>

		<% @order.each do |order| %>

		<div class='form-group'>
			<%= f.label :notes %>
			<%= f.text_field :name, class: "form_control" %>
		</div>

		<%= f.submit "Submit", class: "btn btn-primary" %>

		<% end %>
	</div>
   </div>
</div>

app/views/orders/index.html.erb
<div id="container">
	<%= @orders.inspect %>
	<% @orders.each do |order| %>
		<p><%= "#{order["status"]} - #{order["total"]}" %></p>
	<% end %>
</div>

app/views/orders/new.html.erb
<div id="order-container">

	<div id="user-info">

		<header><h1>Tweet<span>Shirt</span>.io</h1></header>

		<div id="form-container">

			<!--LOGIN FORM-->
			<form id="login_form">
				<div class="twitter-login">
					<h1>Create an Account</h1>
					<span>Or</span>
					<a href="#"><i class="fa fa-twitter"></i> Sign up with Twitter</a>
				</div>
				
					<input name="username" type="text" placeholder="Username">
					<input name="email" type="text" placeholder="Email Address">
					<input name="password" type="text" placeholder="Create Password">
					<input name="confirm_password" type="text" placeholder="Confirm Password">
				
				<button type="submit">Create Account</button>
				<div class="extra">
					<p>Have an account?</p><a href="#">Log In</a>
				</div>
			</form>

			<!--ADDRESS FORM-->
			<form id="address_form" data-remote="true" style="display: none;">
				<input name="street_1" type="text" placeholder="Street Address 1">
				<input name="street_2" type="text" placeholder="Street Address 2">
				<input name="city" type="text" placeholder="City">
				<input name="state" type="text" placeholder="State">
				<input name="zip" type="text" placeholder="Zip">
				<button type="submit">Submit Payment Info</button>
			</form>
				
			<!--SIZE QTY FORM-->	
			<form id="quote_form" data-remote="true" style="display: none;">
				<input name="size" type="text" placeholder="Size">
				<input name="qty" type="number" placeholder="1">
				<button type="submit">Get Quote</button>
			</form>

			<!--CONFIRM PURCHASE FORM-->
			<form id="purchase_form" data-remote="true" style="display: none;">
				<p class="total"></p>
				<button type="submit">Confirm Purchase</button>
			</form>

			<div id="purchase_confirmed" style="display: none;">
				<p>Success</p>
			</div>


		</div><!-- form-containers -->
	</div><!-- user-info -->

	<div id="order-shirt">
		<img src="/assets/shirt.png" />
	</div><!-- order-shirt -->
</div>



<div id="quote" style="display: none;"></div>

app/views/users/index.html.erb
<h1>TweetShirt.io Users</h1>

<% @users.each do |user| %>

<%= image_tag "#{user.profile_image}" %>
<label>Username:</label>
<%= user.username %><br>
<label>Name:</label>
<%= user.name %><br>
<label>Email:</label>
<%= user.email %><br>
<label>Phone:</label>
<%= user.phone_number%><br>
<label>Street Address:</label>
<%= user.street1 %><br>
<label>Suite/Apt Number:</label>
<%= user.street2 %><br>
<label>City:</label>
<%= user.city %><br>
<label>State:</label>
<%= user.state %><br>
<label>Zip:</label>
<%= user.zip %><br><br><br>
<hr>
<label>Current Orders:</label>
orders<br>
<label>Past Ordes:</label>
past orders
<br>
<hr>
<hr>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">

    	<h1>SIGNUP</h1>

			<%= form_for @user, url: { action: "create" } do |f| %>

		    <div class="form-group">
		      	<%= f.label :name%>
		      	<%= f.text_field :name, class: 'form-control' %>
		    </div>

			<div class="form-group">
		        <%= f.label :email %>
				<%= f.text_field :email, class: 'form-control', id: 'inputEmail' %>
			</div>

			<div class="form-group">
				<%= f.label :password %> 
				<%= f.password_field :password, class: "form-control" %>
			</div>
			<div>
				<%= f.submit "Sign up!", class: "btn btn-primary" %>
			</div>

			<div>
			<%= link_to 'Twitter Login', twitter_path %>
			</div>
			
			<% end %>
	</div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>ABOUT TWEETSHIRTS.IO</h1>